services:
  caddy:
    container_name: caddy
    build:
      context: https://github.com/khoadang06/docker.git#main
      dockerfile: caddy/Dockerfile
    restart: unless-stopped
    ports:
      - "8080:80"
      - "8443:443"
      - "8443:443/udp"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - ./caddy/site:/srv
      - caddy_data:/data
      - caddy_config:/config
    networks:
      - caddy_net
    env_file: .env

volumes:
  caddy_data:
  caddy_config:

networks:
  caddy_net:
    name: caddy_net
    driver: bridge
    external: false